style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/GoodwayGroup/gwvault
options:
  commits:
  # filters:
  #   Type:
  #     - feat
  #     - fix
  #     - perf
  #     - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      bugfix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      chore: Chore
      devops: DevOps
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.+)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  merges:
    pattern: "^(.*#\\d+.*)$"
    pattern_maps:
      - Source
  notes:
    keywords:
      - BREAKING CHANGE
